---
title: "R ASCOF Model"
output: html_notebook
---

```{r}
install.packages("tidyverse")

```


```{r}
library(tidyverse)

ascof_df <- read_csv("data/ascof_raw/ascof_sample.csv")
head(ascof_df)
```

```{r}
library(dplyr)

# Filter Response/Non-response = 1
# Filter Support Setting: Residential Care or Nursing Care = [2, 3]
ascof_df <- ascof_df %>% 
  filter(resp == 1) %>%
  filter(SupportSetting == 2 | SupportSetting == 3)
```

```{r}

# Multiple conditions when adding new column to dataframe:
ascof_df <- ascof_df %>% mutate(Q3a_w =               
                     case_when(Q3a == 1 ~ 1, 
                               Q3a == 2 ~ 0.919,
                               Q3a == 3 ~ 0.541,
                               Q3a == 4 ~ 0))  %>%
                     mutate(Q4a_w =
                     case_when(Q4a == 1 ~ 0.911, 
                               Q4a == 2 ~ 0.789,
                               Q4a == 3 ~ 0.265,
                               Q4a == 4 ~ 0.195)) %>%
                     mutate(Q5a_w =
                     case_when(Q5a == 1 ~ 0.879, 
                               Q5a == 2 ~ 0.775,
                               Q5a == 3 ~ 0.294,
                               Q5a == 4 ~ 0.184)) %>%
                     mutate(Q6a_w =
                     case_when(Q6a == 1 ~ 0.863, 
                               Q6a == 2 ~ 0.78,
                               Q6a == 3 ~ 0.374,
                               Q6a == 4 ~ 0.288)) %>%
                     mutate(Q7a_w =
                     case_when(Q7a == 1 ~ 0.88, 
                               Q7a == 2 ~ 0.452,
                               Q7a == 3 ~ 0.298,
                               Q7a == 4 ~ 0.114)) %>%
                     mutate(Q8a_w =
                     case_when(Q8a == 1 ~ 0.873, 
                               Q8a == 2 ~ 0.748,
                               Q8a == 3 ~ 0.497,
                               Q8a == 4 ~ 0.241)) %>%
                       mutate(Q9a_w =
                     case_when(Q9a == 1 ~ 0.962, 
                               Q9a == 2 ~ 0.927,
                               Q9a == 3 ~ 0.567,
                               Q9a == 4 ~ 0.927)) %>%
                       mutate(Q10_w =
                     case_when(Q10 == 1 ~ 0, 
                               Q10 == 2 ~ 0,
                               Q10 == 3 ~ 0,
                               Q10 == 4 ~ 0)) %>%
                       mutate(Q11_w =
                     case_when(Q11 == 1 ~ 0.847, 
                               Q11 == 2 ~ 0.637,
                               Q11 == 3 ~ 0.295,
                               Q11 == 4 ~ 0.263))
head(ascof_df)
```


```{r}
# Calculate current utility weighted care-related quality of life (c_utility)
cols = c('Q3a_w','Q4a_w','Q5a_w','Q6a_w','Q7a_w','Q8a_w','Q9a_w','Q10_w','Q11_w')
ascof_df$c_util <- ascof_df %>% 
  select(cols) %>% 
  transmute(x=rowSums(.)) %>% 
  pull()

ascof_df$c_util <- apply(ascof_df$c_util, 1, function(x) (x*0.203)-0.466, na.rm=TRUE)

#(AL8*0.203)-0.466
head(ascof_df)
```

```{r}
df_join <- stringdist_join(surveyData, carehomesCQC, 
                by = "key",
                mode = "left",
                ignore_case = TRUE, 
                method = "jw", 
                max_dist = 99, 
                distance_col = "dist") %>%
  group_by(key.x) %>%
  slice_min(order_by = dist, n = 1)%>%
  select(key.x, key.y, dist, everything())
```

```{r}
df_join <- df_join[order(df_join$dist),]
df_join <- df_join[(df_join$dist<1),]
dim(df_join)
```

```{r}
write.csv(df_join,"outputs/join.csv", row.names = FALSE)